### PR TITLE
Release 2.0.0 back to develop

### PR DESCRIPTION
**Pull request by lukeindykiewicz**

### CODE REVIEW

**Comment by dilyand** [comment]
@lukeindykiewicz I think this pull request should be closed. Once the release is out and all changes merged to `master`, then you can open a PR from the release branch to `develop`. But having two PRs open and in review simultaneously is confusing and also leads to double work, since any changes in one you must also ensure are also in the other.

**Comment by benjben** [comment]
I agree with @dilyand. I would even say that once we have merged to `master`, we can manually merge to `develop`.

**Comment by dilyand** [comment]
For sure. Once the release is out, the merge back to `develop` is a formality and does not need to go through review.

**Comment by lukeindykiewicz** [comment]
I don't agree, because this release to master should also be just a formality, so both open PRs would be open just for a short while. 

It would not confuse anyone than. It is just a special situation as it was first left untouched for two weeks, than confused of what we do here and recently we found some issues, so it's still open.

I can close this particular one if that will make you happy, but as a general rule I don't agree.

**Pull request closed without merging**
